[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 12.0
normal.family = "DM Mono"
bold.family = "DM Mono"
italic.family = "DM Mono"
bold_italic.family = "DM Mono"

[window]
opacity = 1
