[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
normal.family = "Terminus"
bold.family = "Terminus"
italic.family = "Terminus"
bold_italic.family = "Terminus"

[window]
opacity = 0.8
